# Generated by Django 5.0.14 on 2025-12-30 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cantidad_hectareas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'campos',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cultivos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('es_final', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Laboreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'laboreos',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('superficie_hectareas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='MomentoLaboreo',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'momentos_laboreo',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeLaboreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'ordenes_laboreo',
            },
        ),
        migrations.CreateModel(
            name='ProyectoDeCultivo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'proyectos_cultivo',
            },
        ),
        migrations.CreateModel(
            name='TipoLaboreo',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipos_laboreo',
            },
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Tipos de Suelo',
                'db_table': 'tipos_suelo',
            },
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido'), name='empleado_pk'),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('nombre', 'apellido')},
        ),
        migrations.AddField(
            model_name='laboreo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboreos.empleado'),
        ),
        migrations.AddField(
            model_name='campo',
            name='lotes',
            field=models.ManyToManyField(related_name='+', to='laboreos.lote'),
        ),
        migrations.AddField(
            model_name='ordendelaboreo',
            name='momento_laboreo',
            field=models.ForeignKey(db_column='momento_laboreo_nombre', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboreos.momentolaboreo'),
        ),
        migrations.AddField(
            model_name='laboreo',
            name='orden_laboreo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboreos.ordendelaboreo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='ordenes_laboreo',
            field=models.ManyToManyField(db_table='cultivo_orden_laboreo', related_name='+', to='laboreos.ordendelaboreo'),
        ),
        migrations.AddField(
            model_name='proyectodecultivo',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboreos.cultivo'),
        ),
        migrations.AddField(
            model_name='proyectodecultivo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboreos.estado'),
        ),
        migrations.AddField(
            model_name='proyectodecultivo',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboreos.lote'),
        ),
        migrations.AddField(
            model_name='laboreo',
            name='proyecto_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboreos.proyectodecultivo'),
        ),
        migrations.AddField(
            model_name='ordendelaboreo',
            name='tipo_laboreo',
            field=models.ForeignKey(db_column='tipo_laboreo_nombre', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboreos.tipolaboreo'),
        ),
        migrations.AddField(
            model_name='lote',
            name='tipo_suelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboreos.tiposuelo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo_suelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboreos.tiposuelo'),
        ),
        migrations.AlterUniqueTogether(
            name='laboreo',
            unique_together={('fecha_inicio', 'fecha_fin', 'hora_inicio', 'hora_fin', 'empleado', 'orden_laboreo')},
        ),
        migrations.AddConstraint(
            model_name='ordendelaboreo',
            constraint=models.UniqueConstraint(fields=('orden', 'tipo_laboreo', 'momento_laboreo'), name='orden_laboreo_pk'),
        ),
        migrations.AlterUniqueTogether(
            name='ordendelaboreo',
            unique_together={('orden', 'tipo_laboreo', 'momento_laboreo')},
        ),
    ]
